<?php

return [
    'language' => ['label' => 'Dashboard language', 'hint' => 'The dashboard will open immediately in the selected language.', 'kk' => 'Қазақша', 'ru' => 'Русский', 'en' => 'English', 'save' => 'Save language'],
    'nav' => ['bookings' => 'Bookings', 'calendar' => 'Calendar', 'bonuses' => 'Bonuses', 'settings' => 'Settings', 'reports' => 'Reports'],
    'dashboard' => ['restaurant_cabinet' => 'Restaurant dashboard', 'logout' => 'Log out', 'title' => 'Bookings', 'subtitle' => 'Select a date in the calendar and it will be added to the form on the right.'],
    'calendar' => ['title' => 'Booking calendar', 'previous' => 'Previous month', 'next' => 'Next month', 'today' => 'Today', 'busy' => 'booked', 'weekdays' => ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], 'loading' => 'Loading calendar…', 'error' => 'Could not load the month. Please try again.'],
    'booking' => ['new' => 'New booking', 'date' => 'Date', 'event_type' => 'Event type', 'choose_type' => 'Choose a type', 'visitor' => 'Guest name', 'phone' => 'Phone', 'guests' => 'Number of guests', 'period' => 'Time slot', 'choose_period' => 'Choose a time slot', 'notes' => 'Notes', 'notes_placeholder' => 'Special guest requests', 'save' => 'Save booking', 'selected_day' => 'Events on the selected day', 'no_month' => 'There are no bookings in this month.', 'no_day' => 'There are no events on this day.', 'event' => 'Event', 'not_selected' => 'Time slot not selected', 'not_specified' => 'Not specified', 'none' => 'None', 'status' => 'Status', 'save_changes' => 'Save changes', 'edit' => 'Edit', 'change' => 'Change', 'delete' => 'Delete', 'delete_confirm' => 'Delete this booking?', 'whatsapp_support' => 'Message support on WhatsApp', 'whatsapp' => 'Message on WhatsApp', 'add_event' => 'Add event', 'open_event' => 'Open event', 'close' => 'Close', 'price' => 'Price per guest', 'prepayment' => 'Prepayment', 'total' => 'Total'],
    'event_types' => ['wedding' => 'Wedding', 'birthday' => 'Birthday', 'anniversary' => 'Anniversary', 'corporate' => 'Corporate event', 'other' => 'Other'],
    'status' => ['pending' => 'Awaiting confirmation', 'pending_short' => 'Pending', 'confirmed' => 'Confirmed', 'cancelled' => 'Cancelled'],
    'slots' => ['morning' => 'Morning', 'afternoon' => 'Afternoon', 'evening' => 'Evening'],
    'settings' => ['title' => 'Restaurant settings', 'subtitle' => 'Choose the dashboard language and configure available time slots.', 'slot_time' => 'Time slot', 'default_price' => 'Default price per guest', 'price_hint' => 'You can change this price for each booking.', 'save_time' => 'Save settings', 'logout' => 'Log out'],
    'bonuses' => ['title' => 'Bonuses', 'subtitle' => 'Bonus history and the restaurant’s available balance will appear here.', 'balance' => 'Available balance'],
    'reports' => ['title' => 'Reports', 'subtitle' => 'Filter and export all restaurant bookings by date.', 'from' => 'From', 'to' => 'To', 'period' => 'Time slot', 'all_periods' => 'All time slots', 'show' => 'Show', 'export' => 'Export CSV', 'date' => 'Date', 'event' => 'Event', 'visitor' => 'Guest', 'phone' => 'Phone', 'guests' => 'Guests', 'price' => 'Price/guest', 'prepayment' => 'Prepayment', 'total' => 'Total', 'status' => 'Status', 'notes' => 'Notes', 'empty' => 'There are no bookings yet.'],
    'messages' => ['language_saved' => 'Dashboard language saved.', 'booking_added' => 'Booking added.', 'booking_updated' => 'Booking updated.', 'booking_deleted' => 'Booking deleted.', 'settings_saved' => 'Settings saved.', 'slot_foreign' => 'This time slot does not belong to the restaurant.', 'prepayment_high' => 'Prepayment cannot exceed the total amount.', 'slot_occupied' => 'This time slot is already booked for the selected date.'],
];
