@extends('layouts.store', ['title' => 'Заказ №'.$order->id.' — ZharZhar'])
@section('content')
<div class="shell narrow"><div class="page-heading"><a class="breadcrumb" href="{{ route('store.catalog') }}">← Каталог</a><h1>{{ $order->status === 'paid' ? 'Всё готово к празднику!' : 'Ваше приглашение почти готово' }}</h1><span class="badge badge-{{ $order->status }}">{{ $order->statusLabel() }}</span><p class="hint">Заказ №{{ $order->id }} · {{ $order->details['template_name'] }} · {{ $order->details['names'] }}</p></div>
<div class="stack">
<section class="panel"><h3>Сохраните ссылку на заказ</h3><p class="hint">Здесь можно проверить статус и забрать готовые ссылки. Эта страница личная — не отправляйте её гостям.</p><div class="copy-row"><input aria-label="Личная ссылка на заказ" readonly value="{{ url()->current() }}"><button type="button" class="button outline" data-copy="{{ url()->current() }}">Копировать</button></div></section>
@if($order->status === 'paid')
<section class="panel"><p class="eyebrow">ОПЛАТА ПОДТВЕРЖДЕНА</p><h3>Пригласите тех, кто дорог</h3><p>Отправьте эту ссылку гостям:</p><div class="copy-row"><input aria-label="Ссылка на приглашение" readonly value="{{ $order->publicUrl('i/'.$order->invitation->slug) }}"><button type="button" class="button outline" data-copy="{{ $order->publicUrl('i/'.$order->invitation->slug) }}">Копировать</button></div><p><a class="button primary" href="{{ $order->publicUrl('i/'.$order->invitation->slug) }}">Открыть приглашение ↗</a></p><h3>Ответы гостей — только для вас</h3><p class="hint">Храните эту ссылку в секрете. Любой, у кого она есть, сможет увидеть список гостей.</p><div class="copy-row"><input aria-label="Личная ссылка на ответы" readonly value="{{ $order->publicUrl('responses/'.$order->responses_token) }}"><button type="button" class="button outline" data-copy="{{ $order->publicUrl('responses/'.$order->responses_token) }}">Копировать</button></div><p><a href="{{ $order->publicUrl('responses/'.$order->responses_token) }}">Посмотреть ответы →</a></p></section>
@elseif($order->status === 'rejected')
<section class="panel"><h3>Заказ отклонён</h3><p>{{ $order->admin_note }}</p><p>Если вы уже перевели деньги, свяжитесь с нами по номеру {{ config('store.kaspi_phone') }}, указав номер заказа.</p><a class="button outline" href="{{ route('store.catalog') }}">Вернуться в каталог</a></section>
@else
<section class="panel"><p class="eyebrow">ОПЛАТА ПЕРЕВОДОМ KASPI</p><div class="summary-row"><span>Дизайн</span><strong>{{ number_format($order->subtotal, 0, ',', ' ') }} ₸</strong></div>@if($order->discount)<div class="summary-row"><span>Промокод {{ $order->promo_code }}</span><strong>−{{ number_format($order->discount, 0, ',', ' ') }} ₸</strong></div>@endif<p class="payment-amount">{{ number_format($order->total, 0, ',', ' ') }} ₸</p>
@if($order->total > 0)<p>В Kaspi выберите «Переводы → Клиенту Kaspi» и укажите номер:</p><p class="payment-phone">{{ config('store.kaspi_phone') }}</p><button type="button" class="button outline" data-copy="{{ preg_replace('/[^+0-9]/', '', config('store.kaspi_phone')) }}">Скопировать номер</button><p class="hint">Комментарий к переводу: ZharZhar, заказ №{{ $order->id }}. Перед переводом проверьте номер получателя.</p>@else<p>Промокод покрыл полную стоимость. Отправьте заказ на проверку — перевод не требуется.</p>@endif
@if($order->status === 'pending')
<form method="POST" action="{{ route('store.payment.submit', $order->token) }}" class="stack" data-submit-once>@csrf
<label class="field">{{ $order->total > 0 ? 'Имя отправителя, дата и время перевода' : 'Комментарий к заказу' }}<textarea name="payment_reference" required maxlength="500" placeholder="{{ $order->total > 0 ? 'Например: Айгүл, 12 сентября, 14:35' : 'Оплата полностью покрыта промокодом' }}">{{ old('payment_reference', $order->total === 0 ? 'Оплата полностью покрыта промокодом' : '') }}</textarea>@error('payment_reference')<span class="error">{{ $message }}</span>@enderror</label>
<button class="button primary" type="submit">{{ $order->total > 0 ? 'Я оплатил — отправить на проверку' : 'Отправить заказ на проверку' }}</button></form>
@else<p class="notice">Получили ваше сообщение. После проверки перевода здесь появятся готовые ссылки.</p><p class="hint">{{ $order->payment_reference }}</p><a class="button outline" href="{{ route('store.payment', $order->token) }}">Обновить статус</a>@endif
</section>@endif</div></div>
@endsection
